---
title: "Fitting"
output: html_document
---
# Public version

```{r setup, include=FALSE}
source("libs/Librarries.R")  # comment
source("libs/Accessory/linkfitreal.R")
source("libs/Accessory/simufit.R")
source("libs/plot/compare_mbmf_reg_plot.R")

taskdrug = readRDS("data/taskdrug2.rds")
drug = readRDS("data/drug.rds")
 # pro, dop, plac are refer to the drug conditions propranolol, L-DOPA, Placebo
```

```{r a}
nsub = 30
ndrug = 3
nparam = 2
niter = 100
perfor = matrix(0,ndrug,nsub)
alphafit = matrix(0,ndrug,nsub)
wmbfit = matrix(0,ndrug,nsub)
wmffit = matrix(0,ndrug,nsub)
forgetfit = matrix(0,ndrug,nsub)
prfit = matrix(0,ndrug,nsub)
pzfit = matrix(0,ndrug,nsub)
for (dru in 1:ndrug){
 for (sub in 1:nsub){
    drugpos = drug[sub,dru]
    tasksub = taskdrug[which(taskdrug$subject==sub & taskdrug$day==drugpos), ]
    rewwalk = cbind(tasksub$reward.1, tasksub$reward.2, tasksub$reward.3, tasksub$reward.4)
    trials = cbind(tasksub$trials.1, tasksub$trials.2)
    choicsub = tasksub$choice
    datasub =cbind(rewwalk,trials,choicsub)
    myseed <- 1234
    set.seed(myseed)
   # ctrl <- list( trace = FALSE, itermax = 20) #itermax = 1000,
    
    lower = c(0,0,0,0,0,-100)
    upper = c(1,100,100,1,1,100)
    sn = 10*length(lower)
    
    Npop = as.matrix(t(rbind(
      runif(sn,0,1),
      runif(sn,0,5),
      runif(sn,0,5),
      runif(sn,0,1),
      runif(sn,0,1),
      rnorm(sn,0,1)
      )))
    
    optimize =  DEoptim(
      lower = lower, 
      upper = upper, 
      fn = linkfitreal, 
      datasub = datasub,
      control = DEoptim.control(trace = FALSE, itermax = niter, initialpop=Npop)
    )
    
    
    perfor[dru,sub] = optimize$optim$bestval
    alphafit[dru,sub] = optimize$optim$bestmem[1]
    wmbfit[dru,sub] = optimize$optim$bestmem[1]
    wmffit[dru,sub] = optimize$optim$bestmem[2]
    forgetfit[dru,sub] = optimize$optim$bestmem[4]
    prfit[dru,sub] = optimize$optim$bestmem[5]
    pzfit[dru,sub] = optimize$optim$bestmem[6]
 }
}

fit_param =list(perfor,alphafit,wmbfit,wmffit,forgetfit,prfit,pzfit)
```

# Compare the parameters in three conditions, plots

```{r,fig.width = 5,fig.height = 2}
par_choice = readRDS("data/fit_6param_30sub_100iter.rds")
npar = 7 # 6 + bestfit
prow <- plot_grid(
  compare_mbmf_reg_plot(data.frame(par_choice[[1]][1,], par_choice[[1]][3,], par_choice[[1]][2,])),
  compare_mbmf_reg_plot(data.frame(par_choice[[2]][1,], par_choice[[2]][3,], par_choice[[2]][2,])),
  compare_mbmf_reg_plot(data.frame(par_choice[[3]][1,], par_choice[[3]][3,], par_choice[[3]][2,])),
  compare_mbmf_reg_plot(data.frame(par_choice[[4]][1,], par_choice[[4]][3,], par_choice[[4]][2,])),
  compare_mbmf_reg_plot(data.frame(par_choice[[5]][1,], par_choice[[5]][3,], par_choice[[5]][2,])),
  compare_mbmf_reg_plot(data.frame(par_choice[[6]][1,], par_choice[[6]][3,], par_choice[[6]][2,])),
  compare_mbmf_reg_plot(data.frame(par_choice[[7]][1,], par_choice[[7]][3,], par_choice[[7]][2,])),
  hjust = -1,
  nrow = 2
)
prow
```

# Compare the parameters in three conditions, statistics (Anova,lmer, permutation), section 2.2.1

```{r}
#  Goodness of fit
fit_param = readRDS("data/fit_6param_30sub_100iter.rds") 
subs = c(1:30)
nsub = length(subs)
tot_2opt = c(fit_param[[1]][1,],fit_param[[1]][3,],fit_param[[1]][2,])# Goddness of fit was the firth one
drugname = c(rep("pro", nsub), rep("plac", nsub), rep("dop", nsub))
meta = data.frame(tot_2opt,drugname = as.factor(drugname), subs = as.factor(subs) )
res = aov(tot_2opt~drugname +Error(subs/drugname) , data = meta)
summary(res)


# the lmer orders the conditions from A-Z, and take the first one as the control condition, it is teh reason that i added A,B,C before our drug names
drugname = c(rep("Bpro", nsub), rep("Aplac", nsub), rep("Cdop", nsub))
meta = data.frame(tot_2opt,drugname = as.factor(drugname), subs = as.factor(subs))
# lmer
res = lmer(tot_2opt ~ drugname+ (1|subs) , data = meta)
summary(res)


```

```{r}
# MF weights
fit_param = readRDS("data/fit_6param_30sub_100iter.rds") 
subs = c(1:30)
nsub = length(subs)
tot_2opt = c(fit_param[[4]][1,],fit_param[[4]][3,],fit_param[[4]][2,])# MF weight was the forth one
drugname = c(rep("pro", nsub), rep("plac", nsub), rep("dop", nsub))
meta = data.frame(tot_2opt,drugname = as.factor(drugname), subs = as.factor(subs) )
res = aov(tot_2opt~drugname +Error(subs/drugname) , data = meta)
summary(res)

# the lmer orders the conditions from A-Z, and take the first one as the control condition, it is teh reason that i added A,B,C before our drug names
drugname = c(rep("Bpro", nsub), rep("Aplac", nsub), rep("Cdop", nsub))
meta = data.frame(tot_2opt,drugname = as.factor(drugname), subs = as.factor(subs))
# lmer
res = lmer(tot_2opt ~ drugname+ (1|subs) , data = meta)
summary(res)


```

```{r}
# MB weights
fit_param = readRDS("data/fit_6param_30sub_100iter.rds") 
subs = c(1:30)
nsub = length(subs)
tot_2opt = c(fit_param[[3]][1,],fit_param[[3]][3,],fit_param[[3]][2,]) # MB weight was the third one
drugname = c(rep("pro", nsub), rep("plac", nsub), rep("dop", nsub))
meta = data.frame(tot_2opt,drugname = as.factor(drugname), subs = as.factor(subs) )
res = aov(tot_2opt~drugname +Error(subs/drugname) , data = meta)
cmbfval = summary(res)[[1]][[2,"F value"]]
cmbpval = summary(res)[[1]][[2,"Pr(>F)"]]
print(paste0("F: ", cmffval, " P: ", cmfpval))


# the lmer orders the conditions from A-Z, and take the first one as the control condition, it is teh reason that i added A,B,C before our drug names
drugname = c(rep("Bpro", nsub), rep("Aplac", nsub), rep("Cdop", nsub))
meta = data.frame(tot_2opt,drugname = as.factor(drugname), subs = as.factor(subs))
# lmer
res = lmer(tot_2opt ~ drugname+ (1|subs) , data = meta)
summary(res)
```

# comparing the MB contribution across three conditions for the simulated behavior from model
```{r}
randeff = readRDS("data/mixedreg_MBcont_1000simu.rds")
randof = apply(randeff,c(1,3), mean)
nsub=30
subs = c(1:nsub)
tot_2opt = c(randof[1,subs],randof[3,subs],randof[2,subs])
drugname = c(rep("pro", nsub), rep("plac", nsub), rep("dop", nsub))
meta = data.frame(tot_2opt,drugname = as.factor(drugname), subs= as.factor(subs) )
res = aov(tot_2opt~drugname+ Error(subs/drugname) , data = meta) 
summary(res)

# the lmer orders the conditions from A-Z, and take the first one as the control condition, it is teh reason that i added A,B,C before our drug names
drugname = c(rep("Bpro", nsub), rep("Aplac", nsub), rep("Cdop", nsub))
meta = data.frame(tot_2opt,drugname = as.factor(drugname), subs = as.factor(subs))
# lmer
res = lmer(tot_2opt ~ drugname+ (1|subs) , data = meta)
summary(res)
```


